### ISSUE TITLE
Language and Step confusion | 语言和步骤混乱 

### ISSUE THREAD

**Issue by ghost** [vicosna/termius-cracked#4]
I am an english reader, after converting Chinese language into English, I came to know, to delete .asar file. But after that, I do not know what to do and how to do.
Kindly specify the steps clearly and in english if possible.

**Comment by ghost** [comment]
我是英文读者，把中文转英文后才知道，要删除.asar文件。但在那之后，我不知道该怎么做，该怎么做。
如果可能，请用英文清楚地说明步骤。

**Comment by bestv5** [comment]
I added an English description, most of which comes from online translation, if there is an error, please correct me .
see  `readme_en.md`  in  [pull request ](https://github.com/vicosna/termius-cracked/pull/5 )
